spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthDuo?useSSL=false&allowPublicKeyRetrieval=true
    username: intae
    password: dD7904258!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
logging:
  level:
    root: info
    org.hibernate.SQL: debug
